project:
  type: website
  output-dir: docs
  
website:
  title: "PA 446 website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "About"
        href: about.qmd
      - text: "Spring 2024"
        href: spring-2024.qmd


format:
  html:
  theme: sandstone
  mainfont:arial
  fontsize:1.5rem
  fontcolor:"#9C3C27"
    css: styles.css
    toc: true