project:
  type: website
  output-dir: docs
  
website:
  title: "PA 446 website"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "About"
      - about.qmd
        - spring2024.qmd


format:
   html:
     theme:sandstone
  mainfont:arial
  fontsize:1.5rem
  linkcolor:#"ff33f0"
  fontcolor:"#9C3C27"
  monofont: courier new
    css: styles.css
    toc: true